import Head from 'next/head'
import Header from '@/components/Header'
import Hero from '@/components/Hero'
import About from "@/components/About";
import React from "react";
import Experiences from "@/components/Experiences";
import Educations from "@/components/Educations";
import Projects from "@/components/Projects";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <div className='min-h-screen bg-[#110626] px-44'>
                    <Header/>
                    <Hero/>
                    <About/>
                    <Experiences/>
                    <Educations/>
                    <Projects/>
                    <div className='pt-44'>
                        <h4 className={'uppercase text-4xl text-[#F9F871] mb-10'}>Contact</h4>
                    </div>
                </div>
            </main>
        </>
    )
}


