import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/components/header'
import Hero from '@/components/Hero'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='min-h-screen bg-[#110626] px-24'>
          <Header/>
          <Hero/>
          <div className='h-[calc(100vh-74px)] pt-10'>
            <h4 className='uppercase text-4xl text-[#F9F871]'>About</h4>
          </div>
        </div>
      </main>
    </>
  )
}
